apps/cheques/urls.py
from django.urls import path

from apps.cheques import views

urlpatterns = [
    path('customers/cheques/fbv/', views.display_cheques, name='display_cheques'),
]

apps/customers/urls.py
from django.urls import path

from apps.customers import views

urlpatterns = [
    # path("members/",                InstitutionListView.as_view(),      name="institutions-list"),
    # path("filter/instructions/",    InstitutionFilterView.as_view(),    name="institutions-filter"),
    # path("create/institution/",     InstitutionCreateView.as_view(),    name="institution-create"),
    # path("<slug:slug>/",            InstitutionDetailView.as_view(),    name="institution-detail"),

    path('customers/fbv/', views.display_customers, name='display_customers'),
    # path('members/<int:id>/delete/', views.delete_institution, name='delete_institution'),
]

apps/facilities/urls.py
from django.urls import path

from apps.facilities import views

urlpatterns = [
    path('customers/facilities/fbv/', views.display_facilities, name='display_facilities'),
]

apps/members/api/urls.py
from django.urls import path

from apps.members.api.views import hello_world

urlpatterns = [
    path('api/', hello_world),
]

apps/members/urls.py
from django.urls import path

from apps.members import views
from apps.members.views import InstitutionListView, InstitutionFilterView, InstitutionCreateView, InstitutionDetailView

urlpatterns = [
    path("members/",                InstitutionListView.as_view(),      name="institutions-list"),
    path("filter/instructions/",    InstitutionFilterView.as_view(),    name="institutions-filter"),
    path("create/institution/",     InstitutionCreateView.as_view(),    name="institution-create"),
    path("<slug:slug>/",            InstitutionDetailView.as_view(),    name="institution-detail"),

    path('members/fbv/', views.display_institutions, name='display_institutions'),
    path('members/<int:id>/delete/', views.delete_institution, name='delete_institution'),
]

django_pro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),

    path('', include('apps.members.api.urls')),

    path('', include('apps.members.urls')),
    path('', include('apps.customers.urls')),
    path('', include('apps.facilities.urls')),
    path('', include('apps.cheques.urls')),
]

apps/cheques/models.py
from django.db import models

# Create your models here.

apps/customers/models.py
from django.db import models

# Create your models here.

apps/facilities/models.py
from django.db import models

# Create your models here.

apps/members/models/institution.py
"""Members app models"""
from django.db import models
from django.urls import reverse

from apps.models.commons import SoftDeletionModel


class Institution(SoftDeletionModel):
    """Members Institution model class"""
    name = models.CharField(max_length=64, db_index=True)
    old_name = models.CharField(max_length=64, db_index=True)
    slug = models.CharField(max_length=128)

    @property
    def is_active(self):
        return self.deleted_at is None

    def get_absolute_url(self) -> str:
        return reverse("institution-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name

apps/models/commons.py
from django.db import models
from django.db.models import QuerySet
from django.utils import timezone


class SoftDeletionQuerySet(QuerySet):
    def delete(self):
        return super(SoftDeletionQuerySet, self).update(deleted_at=timezone.now())

    def alive(self):
        return self.filter(deleted_at=None)

    def dead(self):
        return self.exclude(deleted_at=None)


class SoftDeletionManager(models.Manager):
    def __init__(self, *args, **kwargs):
        self.alive_only = kwargs.pop('alive_only', True)
        super(SoftDeletionManager, self).__init__(*args, **kwargs)

    def get_queryset(self):
        if self.alive_only:
            return SoftDeletionQuerySet(self.model).filter(deleted_at=None)
        return SoftDeletionQuerySet(self.model)


class SoftDeletionModel(models.Model):
    deleted_at = models.DateTimeField(blank=True, null=True)

    objects = SoftDeletionManager()
    all_objects = SoftDeletionManager(alive_only=False)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()

apps/members/forms.py
from django import forms
from django.utils.text import slugify

from apps.members.models import Institution


class InstitutionCreateForm(forms.ModelForm):
    slug = forms.CharField(required=False, widget=forms.widgets.HiddenInput())

    class Meta:
        model = Institution
        fields = ("name", "slug")

    def clean_name(self) -> str:
        name: str = self.cleaned_data["name"]
        slug = slugify(name)
        if Institution.objects.filter(slug=slug).exists():
            raise forms.ValidationError(f"An Institution with the name {name} exists")
        return name

    def save(self, commit: bool = True) -> Institution:
        institution: Institution = super().save(commit)
        institution.slug = slugify(institution.name)
        institution.save()
        return institution

apps/cheques/views.py
from django.shortcuts import render


# Create your views here.

def display_cheques(request):
    # institutions = Institution.objects.all()
    return render(
        request, 'display_cheques.html',
        # {'institutions': institutions},
    )

apps/customers/views.py
from django.shortcuts import render

# Create your views here.


def display_customers(request):
    # institutions = Institution.objects.all()

    if request.META.get("HTTP_HX_REQUEST") != 'true':
        return render(request, 'display_customers_full.html')

    return render(
        request, 'display_customers.html',
        # {'institutions': institutions},
    )

apps/facilities/views.py
from django.shortcuts import render


# Create your views here.

def display_facilities(request):
    # institutions = Institution.objects.all()
    return render(
        request, 'display_facilities.html',
        # {'institutions': institutions},
    )

apps/members/api/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response


@api_view()
@permission_classes([AllowAny])
def hello_world(request):
    return Response({"message": "Hello, world!"})

apps/members/views.py
"""Members app views"""
import json
from typing import Dict, Any

from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView, CreateView, DetailView
from django_filters.views import FilterView

from apps.members.filters import InstitutionFilter
from apps.members.forms import InstitutionCreateForm
from apps.members.models import Institution


class InstitutionListView(ListView):
    model = Institution

    def get_context_data(self, **kwargs: Dict[str, Any]) -> Dict[str, Any]:
        return super().get_context_data(
            form=InstitutionCreateForm(), filterset=InstitutionFilter, **kwargs
        )


class InstitutionFilterView(FilterView):
    filterset_class = InstitutionFilter


class InstitutionCreateView(CreateView):
    model = Institution
    form_class = InstitutionCreateForm
    template_name = "members/institution_create_form.html"

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        institution = form.save()
        response = HttpResponse()
        response["HX-Trigger"] = json.dumps(
            {"redirect": {"url": institution.get_absolute_url()}}
        )
        return response


class InstitutionDetailView(DetailView):
    model = Institution


def display_institutions(request):
    institutions = Institution.objects.all()
    return render(request, 'display_institutions.html', {'institutions': institutions})


@require_http_methods(['DELETE'])
def delete_institution(request, id):
    Institution.objects.filter(id=id).delete()
    institutions = Institution.objects.all()
    return render(request, 'members_list.html', {'institutions': institutions})

apps/cheques/templates/display_cheques.html
{% extends "base.html" %}

{% block main %}
    <h1>Dishonored Instruments</h1>
{#    {% include "members_list.html" %}#}
{% endblock %}

apps/customers/templates/display_customers.html
    <h1>Credit Customers</h1>

apps/customers/templates/display_customers_full.html
{% extends "base.html" %}

{% block main %}
    {% include "display_customers.html" %}
{% endblock %}

apps/facilities/templates/display_facilities.html
{% extends "base.html" %}

{% block main %}
    <h1>Credit Customers' Facilities</h1>
{#    {% include "members_list.html" %}#}
{% endblock %}

apps/members/templates/display_institutions.html
{% extends "base.html" %}

{% block main %}
    <h1>Member Institutions</h1>
    {% include "members_list.html" %}
{% endblock %}

apps/members/templates/institutions_list.html
<div id="institutions"
  hx-confirm="Are you sure you want to delete this task?"
  hx-target="#institutions"
  hx-swap="outerHTML">
  {% for institution in institutions %}
    <div>{{ forloop.counter }} {{ institution.name }}
      <a class="block mr-2 hover:text-gray-600"
        hx-delete="{% url 'delete_institution' institution.id %}">
        Delete?
      </a>
    </div>
  {% endfor %}
</div>

apps/members/templates/members/institution_create_form.html
<div id="institution-form">
  <form>
    {% csrf_token %}
    <div class="form-row mb-2">
      <div class="col">
        <input class="form-control
          {% if form.name.errors %}
            is-invalid
          {% endif %}
          " id="id_name" name="name"
               placeholder="Name" {% if form.name.value %} value="{{ form.name.value }}"
          {% endif %}>
        <div class="invalid-feedback">
          {{ form.name.errors }}
        </div>
      </div>
    </div>

    <div class="form-row mb-2">
      <div class="col">
        <input class="form-control
          {% if form.old_name.errors %}
            is-invalid
          {% endif %}
          " id="id_old_name" name="old_name"
               placeholder="Old Name" {% if form.old_name.value %} value="{{ form.old_name.value }}"
          {% endif %}>
        <div class="invalid-feedback">
          {{ form.old_name.errors }}
        </div>
      </div>
    </div>

    <div class="form-row">
      <div class="col">
        <button class="btn btn-primary" hx-post="{% url 'institution-create' %}" hx-swap="outerHTML"
          hx-target="#institution-form">Create</button>
      </div>
    </div>

  </form>
</div>

apps/members/templates/members/institution_detail.html
{% extends "base.html" %}

{% block main %}
<div class="card">
    <h3>{{ institution.name }}</h3>
{#  <table class="table table-striped m-0">#}
{#    <thead>#}
{#      <tr>#}
{#        <th class="border-0" scope="col">{{ institution.name }}</th>#}
{#      </tr>#}
{#    </thead>#}
{#    <tbody id="tasklist-tasks">#}
{#      {% include "tasks/tasklist_tasks.html" with tasklist=tasklist %}#}
{#    </tbody>#}
{#  </table>#}
  <div class="card-body px-3">
{#    <form hx-post="{% url 'tasklist-add-task' slug=tasklist.slug %}" hx-target="#tasklist-tasks">#}
{#      {% csrf_token %}#}
{#      <button type="submit" class="btn btn-outline-primary btn-sm">#}
{#        <i class="fas fa-plus"></i>#}
{#        Add Task#}
{#      </button>#}
{#    </form>#}
  </div>
</div>
{% endblock %}

apps/members/templates/members/institution_list.html
{% extends "base.html" %}


{% block main %}
<div class="row mb-2">
  <div class="col-9">

    <form hx-trigger="keyup,mouseup delay:100ms"
          hx-get="{% url 'institutions-filter' %}"
          hx-target="#institutions-table">

      <div class="form-row">
        <div class="col">
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-search"></i></div>
            </div>
            <input name="name" class="form-control" id="id_name" placeholder="Search Institution">
          </div>
        </div>
{#        <div class="col pt-2">#}
{#          {% for choice in filterset.form.completeness.field.choices %}#}
{#          <div class="form-check form-check-inline">#}
{#            <input class="form-check-input" type="radio"#}
{#                   name="completeness" id="id_completeness_{{ forloop.counter }}"#}
{#              value="{{ choice.0 }}" {% ifequal forloop.counter 1 %}checked{% endifequal %}>#}
{#            <label class="form-check-label"#}
{#                   for="id_completeness_{{ forloop.counter }}">{{ choice.1 }}</label>#}
{#          </div>#}
{#          {% endfor %}#}
{#        </div>#}
      </div>

    </form>
  </div>



  <div class="col-3 text-right">
    <!-- Example single danger button -->
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createModal">
      <i class="fas fa-plus"></i>
      Create Institution
    </button>

    <!-- Modal -->
    <div class="modal fade" id="createModal" tabindex="-1"
         aria-labelledby="createModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header border-0 pb-0">
            <h5 class="modal-title" id="createModalLabel">Create Institution</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% include "members/institution_create_form.html" %}
          </div>
        </div>
      </div>
    </div>

  </div>

</div>

<div id="institutions-table">
  {% include "members/institutions_filter.html" with object_list=object_list %}
</div>

{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
  document.addEventListener("redirect", evt => {
    console.log(evt);
    window.location.href = evt.detail.url;
  });
  htmx.logAll();
</script>
{% endblock %}

apps/members/templates/members/institutions_filter.html
<div class="card">
  <table class="table table-striped m-0">
    <thead>
      <tr>
        <th class="border-0" scope="col">Name</th>
{#        <th class="border-0" scope="col">Incomplete Tasks</th>#}
{#        <th class="border-0" scope="col">Complete Tasks</th>#}
      </tr>
    </thead>
    <tbody>
      {% for institution in object_list %}
      <tr>
        <th class="border-0" scope="row">
          <a href="{{ institution.get_absolute_url }}">
            {{ institution.name }}
          </a>
        </th>
{#        <td class="border-0">{{ institution.complete_tasks.count }}</td>#}
{#        <td class="border-0">{{ institution.incomplete_tasks.count }}</td>#}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

apps/members/templates/members_list.html
<div id="institutions"
  hx-confirm="Are you sure you want to delete this task?"
  hx-target="#institutions"
  hx-swap="outerHTML">
  {% for institution in institutions %}
    <div>{{ forloop.counter }} {{ institution.name }}
      <a class="block mr-2 hover:text-gray-600"
        hx-delete="{% url 'delete_institution' institution.id %}">
        Delete?
      </a>
    </div>
  {% endfor %}
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" crossorigin="anonymous">

    <script src="{% static 'js/2aaa0bfb6c.js' %}" crossorigin="anonymous" ></script>


    <title>Title</title>
</head>
<body>
    <div class="container">
        <div class="row my-3">
            <div class="col">
                <a href="{% url 'institutions-list' %}">
                    <h3><i class="fas fa-building"></i> Member Institutions</h3>
                </a>
            </div>

            <div class="col">
                <a hx-get="{% url 'display_customers' %}" hx-push-url="true"
                hx-target="#content" hx-swap="outerHTML"
                hx-indicator="#content-loader">
                    <h3><i class=""></i> Customers</h3>
                </a>
            </div>

            <div class="col">
                <a hx-get="{% url 'display_facilities' %}" hx-push-url="true"
                hx-target="#content" hx-swap="outerHTML"
                hx-indicator="#content-loader">
                    <h3><i class=""></i> Facilities</h3>
                </a>
            </div>

            <div class="col">
                <a hx-get="{% url 'display_cheques' %}" hx-push-url="true"
                hx-target="#content" hx-swap="innerHTML"
                hx-indicator="#content-loader">
                    <h3><i class=""></i> Cheques</h3>
                </a>
            </div>

        </div>
        <progress id="content-loader" class="htmx-indicator" max="100"></progress>
        <div id="content">{% block main %}{% endblock %}</div>

    </div>
    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" crossorigin="anonymous"></script>

    {% block extrascripts %}
    {% endblock %}
</body>
</html>